version: "3"
services:
  PostgreSQL:
    restart: always
    image: postgres:13.2
    environment:
      - POSTGRES_PASSWORD=pass123
    ports:
      - "5432:5432"
  test-db:
    image: postgres:13.2
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=pass123
